export type IncomeItem = {
  id: number
  month: string
  type: string
  subclass: string
  payer: string
  income: number
  socialInsurance: number
  deduction: number
  showArrow: boolean
}
export const rawIncomeEntries: IncomeItem[] = [
  {
    id: 20221201,
    month: '2022-12',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 17000,
    socialInsurance: 2680,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20221202,
    month: '2022-12',
    type: '工资薪金',
    subclass: '所得项目小类：季度奖金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 7500,
    socialInsurance: 0,
    deduction: 0,
    showArrow: true,
  },
  {
    id: 20221101,
    month: '2022-11',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16850,
    socialInsurance: 2650,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20221001,
    month: '2022-10',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16700,
    socialInsurance: 2620,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220901,
    month: '2022-09',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16600,
    socialInsurance: 2600,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220902,
    month: '2022-09',
    type: '工资薪金',
    subclass: '所得项目小类：季度奖金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 6800,
    socialInsurance: 0,
    deduction: 0,
    showArrow: true,
  },
  {
    id: 20220801,
    month: '2022-08',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16550,
    socialInsurance: 2580,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220701,
    month: '2022-07',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16400,
    socialInsurance: 2550,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220601,
    month: '2022-06',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16350,
    socialInsurance: 2530,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220602,
    month: '2022-06',
    type: '工资薪金',
    subclass: '所得项目小类：季度奖金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 7200,
    socialInsurance: 0,
    deduction: 0,
    showArrow: true,
  },
  {
    id: 20220501,
    month: '2022-05',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16200,
    socialInsurance: 2500,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220401,
    month: '2022-04',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16100,
    socialInsurance: 2480,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220301,
    month: '2022-03',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 16050,
    socialInsurance: 2450,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220302,
    month: '2022-03',
    type: '工资薪金',
    subclass: '所得项目小类：季度奖金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 6400,
    socialInsurance: 0,
    deduction: 0,
    showArrow: true,
  },
  {
    id: 20220201,
    month: '2022-02',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 15950,
    socialInsurance: 2430,
    deduction: 5000,
    showArrow: true,
  },
  {
    id: 20220101,
    month: '2022-01',
    type: '工资薪金',
    subclass: '所得项目小类：正常工资薪金',
    payer: '扣缴义务人：深圳市和合信诺有限…',
    income: 15800,
    socialInsurance: 2400,
    deduction: 5000,
    showArrow: true,
  },
]

// const rawIncomeEntries: IncomeItem[] = [
//   {
//     id: 20231201,
//     month: '2023-12',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3100,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20231202,
//     month: '2023-12',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20231203,
//     month: '2023-12',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20231204,
//     month: '2023-12',
//     type: '工资薪金',
//     subclass: '所得项目小类：季度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 8000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20231101,
//     month: '2023-11',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3090,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20231102,
//     month: '2023-11',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20231103,
//     month: '2023-11',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20231001,
//     month: '2023-10',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3095,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20231002,
//     month: '2023-10',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20231003,
//     month: '2023-10',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230901,
//     month: '2023-09',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3080,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230902,
//     month: '2023-09',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230903,
//     month: '2023-09',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230904,
//     month: '2023-09',
//     type: '工资薪金',
//     subclass: '所得项目小类：季度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 8000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230801,
//     month: '2023-08',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3075,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230802,
//     month: '2023-08',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230803,
//     month: '2023-08',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230701,
//     month: '2023-07',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3070,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230702,
//     month: '2023-07',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230703,
//     month: '2023-07',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230601,
//     month: '2023-06',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3060,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230602,
//     month: '2023-06',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230603,
//     month: '2023-06',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230604,
//     month: '2023-06',
//     type: '工资薪金',
//     subclass: '所得项目小类：季度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 8000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230501,
//     month: '2023-05',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3050,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230502,
//     month: '2023-05',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230503,
//     month: '2023-05',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230401,
//     month: '2023-04',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3040,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230402,
//     month: '2023-04',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230403,
//     month: '2023-04',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230301,
//     month: '2023-03',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3035,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230302,
//     month: '2023-03',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230303,
//     month: '2023-03',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230304,
//     month: '2023-03',
//     type: '工资薪金',
//     subclass: '所得项目小类：季度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 8000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230201,
//     month: '2023-02',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3025,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230202,
//     month: '2023-02',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230203,
//     month: '2023-02',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
//   {
//     id: 20230101,
//     month: '2023-01',
//     type: '工资薪金',
//     subclass: '所得项目小类：正常工资薪金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 17000,
//     socialInsurance: 3010,
//     deduction: 5000,
//     showArrow: true,
//   },
//   {
//     id: 20230102,
//     month: '2023-01',
//     type: '工资薪金',
//     subclass: '所得项目小类：月度绩效奖金',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 13000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: true,
//   },
//   {
//     id: 20230103,
//     month: '2023-01',
//     type: '工资薪金',
//     subclass: '所得项目小类：专项补贴',
//     payer: '扣缴义务人：北京字节跳动科技有限公司',
//     income: 9000,
//     socialInsurance: 0,
//     deduction: 0,
//     showArrow: false,
//   },
// ]
